# Specifies the name of the action
name: Continuous Deployment to Google App Engine
# Specifies that the action should be ran on all pushes to the main branch
on:
  push:
    branches:
      - main
# Specifies the `jobs` to be executed for this action
jobs:
  build:
    name: Google App Engine Continuous Deployment
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v2
      # Deploys your project to GAE using github secret 
      - uses: google-github-actions/deploy-appengine@main
        with:
          # Use the GitHub secret "gcloud_secret" as credentials
          credentials: ${{ secrets.gcloud_secret }}
          # Specifies path to working directory (source files for project)
          working_directory: ./src/
          # Path to config file needed for deployment on GAE (Path relative to working directory)
          deliverables: app.yaml