name: Continous Deployment to Google App Engine
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Google App Engine Countinous Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.gcloud_secret }}
          deliverables: app.yaml
          working_directory: ./src/